apiVersion: ENC[AES256_GCM,data:i6U=,iv:e93gzTki6wV1GOnSw+1g3KJqVbKJnOAImQ6p6XudKH0=,tag:E9c6Ihpv1W6viDIEGAIMjA==,type:str]
kind: ENC[AES256_GCM,data:uQnXDBxR,iv:vZrLMVJZRkOV/fwPXx/evHXu6Pem1KNMVtp7zCCpoDg=,tag:cWRtoUWOKa8JadiqWmpcLg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zyhVHekdSTQjyBA=,iv:Ny9MDMZ7a8yqG1iHFE6/ikGtcopuyHvSgE7113mkL1A=,tag:189ejsb9WGCASSglaRlO3A==,type:str]
    namespace: ENC[AES256_GCM,data:0cU/UbCJSPmK6djkRA==,iv:jX3e7qwRcraht398llznQ8pGOjL59Ayixts9EpPcLWs=,tag:d+BIvfqDAGbCzXmwSlDyjw==,type:str]
type: ENC[AES256_GCM,data:/5xNcNVP,iv:Cy7XmNePZukfYaUW82eWNMZAx51XV48OBfuDF5J7uS8=,tag:oAH4QTOt+kLi+b1zXAum+g==,type:str]
stringData:
    password: ENC[AES256_GCM,data:GMd4L2uWyI3DRg==,iv:bphDac5kXNmjz2IUfZCagyIIBbnzAewSAqbhAm1EoZY=,tag:EZd1ix3ZZa6H1MqqOGtFzQ==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2026-02-21T17:28:26Z"
          enc: bs0KTDPJjJOGtO6rqoh_0FWzpYUq0XCPYfZUJa8wTbuTeD8AxxTpqxy4KeZCNAOsD-pa6zDnLRWXF-tsnu0mmDrGHnTzMMEe8uFK7N1tqfhj4GICpomGq5VhxgvNjW9V3h9dubFbImR6hXr3S8fo5jFa5S01urFlJfIU4G4elEA3Fc1mEg3jGYpHblDgVDC8UD9mdXgKTbBCJCklvr46gEiROpnljHaiXq4EhTWVxFw15qoX7V6AcJTPdx_C0bnw8DuW1lbk1jTiaSx4OOuLomvc2y3BxGt5LvIkQuGy-ikXnQbFKNSOkS4XC_mLFfV7yGQp7D7jwPwc3MGyvb8f5A
    lastmodified: "2026-02-21T17:28:34Z"
    mac: ENC[AES256_GCM,data:4ksmm7v6Ilob2yc4FnHIi4igAtf4gHx9jSSNNCFvstQNDkKsLOcpiCPGqlsAMm1wpXtmV4D53vHd2MmM8LFPpsyT5n6cwMBYC+Djl6Bmk5POFnisyRD1W92ZtEyoGngs7pCG/jjqHVbyqlICGE2wPYpGO1oOHrJ8ewcXoLCJMW0=,iv:exP/EVdOOYbf1ckJ1ZB8Eg3uqtSKA4fSWMQm1kS1QuY=,tag:+i44ZsLY86pPrt2Cc+++1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
---
apiVersion: ENC[AES256_GCM,data:ke4=,iv:s6FynjDrnyytpOLTymO4lHszB+pUckBjK3cbvY9E348=,tag:8MtAv/PsKnakQOjs7DEbYA==,type:str]
kind: ENC[AES256_GCM,data:FsuW6ugF,iv:9MvwZtvyNRbjVVnPO6cERUk5UIyvzl19WBdTmcW2EI8=,tag:AYKM81nI8LpsFxr/o40u+w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Bk3hbvUEiW8=,iv:BZeM6Fg2I+3qMt14/XAkywLtdEJPHf/NkgJpXMQz0Ms=,tag:3Jtz8fb/inyVqBM1E0mgYA==,type:str]
    namespace: ENC[AES256_GCM,data:4qn+3C8RwGlBzuXskw==,iv:ridIzE/wqWQmVKGhpOFTuIb38Yff4G78lYSmAZtVd04=,tag:M4gyhImeWDrvDQqB8THB6g==,type:str]
type: ENC[AES256_GCM,data:Nd3hT3Wb,iv:cEXOdV8mcY/rlSsiL4lvMgdZYYHaLDGesqyTfUH4XY8=,tag:q4kPN8mn1x5iXWaBrS00Ng==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:Zt8lRxWv2EcyAy7hEb8nAg==,iv:YfEpvb2wpDzTqI85vt+Ts7x6kJblgCLqfzaNwARChK8=,tag:kIItm5Ifl1fIreyz+3lepA==,type:str]
    secretKey: ENC[AES256_GCM,data:DrafxFfZGyD4LcxDYx/2/Q==,iv:KbRO3qVpLHRQPOjG/hYFtCAtGF0r7uAXc8kBM/u1SqQ=,tag:IxMmnd7QadHpzWmpm/RhuQ==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2026-02-21T17:28:26Z"
          enc: bs0KTDPJjJOGtO6rqoh_0FWzpYUq0XCPYfZUJa8wTbuTeD8AxxTpqxy4KeZCNAOsD-pa6zDnLRWXF-tsnu0mmDrGHnTzMMEe8uFK7N1tqfhj4GICpomGq5VhxgvNjW9V3h9dubFbImR6hXr3S8fo5jFa5S01urFlJfIU4G4elEA3Fc1mEg3jGYpHblDgVDC8UD9mdXgKTbBCJCklvr46gEiROpnljHaiXq4EhTWVxFw15qoX7V6AcJTPdx_C0bnw8DuW1lbk1jTiaSx4OOuLomvc2y3BxGt5LvIkQuGy-ikXnQbFKNSOkS4XC_mLFfV7yGQp7D7jwPwc3MGyvb8f5A
    lastmodified: "2026-02-21T17:28:34Z"
    mac: ENC[AES256_GCM,data:4ksmm7v6Ilob2yc4FnHIi4igAtf4gHx9jSSNNCFvstQNDkKsLOcpiCPGqlsAMm1wpXtmV4D53vHd2MmM8LFPpsyT5n6cwMBYC+Djl6Bmk5POFnisyRD1W92ZtEyoGngs7pCG/jjqHVbyqlICGE2wPYpGO1oOHrJ8ewcXoLCJMW0=,iv:exP/EVdOOYbf1ckJ1ZB8Eg3uqtSKA4fSWMQm1kS1QuY=,tag:+i44ZsLY86pPrt2Cc+++1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
