apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-pv
spec:
  capacity:
    storage: {{ .Values.mssql.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mssql"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ index .Values.mssql.nodeSelector "kubernetes.io/hostname" }}
  persistentVolumeReclaimPolicy: Retain
