bases:
  - environments.yaml

helmDefaults:
  wait: true
  timeout: 600
  cleanupOnFail: true
  atomic: true

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: apache-airflow
    url: https://airflow.apache.org
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: external-secrets
    url: https://charts.external-secrets.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: spark-operator
    url: https://kubeflow.github.io/spark-operator
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    version: 1.16.3
    namespace: cert-manager
    createNamespace: true
    labels:
      app: cert-manager
      tier: infra
    values:
      - services/cert-manager/cert-manager.values.yaml.gotmpl

  - name: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    namespace: ingress-nginx
    createNamespace: true
    labels:
      app: ingress-nginx
      tier: infra
    values:
      - services/ingress-nginx/ingress-nginx.values.yaml.gotmpl

  - name: external-secrets
    chart: ./services/external-secrets
    namespace: external-secrets
    createNamespace: true
    labels:
      app: external-secrets
      tier: infra
    values:
      - services/external-secrets/external-secrets.operator.values.yaml.gotmpl

  - name: external-secrets-resources
    chart: ./services/external-secrets
    namespace: "{{ .Environment.Values.global.namespace }}"
    createNamespace: true
    labels:
      app: external-secrets
      tier: infra
    values:
      - services/external-secrets/external-secrets.values.yaml.gotmpl
    secrets:
      - services/external-secrets/external-secrets.credentials.yaml
    needs:
      - external-secrets/external-secrets

  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    version: 80.6.0
    namespace: "{{ .Environment.Values.monitoring.namespace }}"
    createNamespace: true
    labels:
      app: monitoring
      tier: observability
    values:
      - services/monitoring/kube-prometheus-stack.values.yaml.gotmpl
    secrets:
      - services/monitoring/grafana.credentials.yaml
    needs:
      - "{{ .Environment.Values.global.namespace }}/ingress-resources"
      - ingress-nginx/ingress-nginx

  - name: spark-operator
    chart: spark-operator/spark-operator
    version: 2.4.0
    namespace: spark-operator
    createNamespace: true
    labels:
      app: spark-operator
      tier: data-processing
    values:
      - services/spark-operator/spark-operator.values.yaml.gotmpl

  - name: spark-connect
    chart: ./services/spark-connect
    namespace: "{{ .Environment.Values.global.namespace }}"
    createNamespace: true
    labels:
      app: spark-connect
      tier: data-processing
    values:
      - services/spark-connect/spark-connect.values.yaml.gotmpl
    needs:
      - "{{ .Environment.Values.global.namespace }}/ivy-cache"
      - "{{ .Environment.Values.global.namespace }}/minio"
      - "{{ .Environment.Values.global.namespace }}/ingress-resources"
      - ingress-nginx/ingress-nginx

  - name: unity-catalog
    chart: ./services/unity-catalog
    namespace: "{{ .Environment.Values.unityCatalog.namespace }}"
    createNamespace: true
    labels:
      app: unity-catalog
      tier: governance
    values:
      - services/unity-catalog/unity-catalog.values.yaml.gotmpl
    needs:
      - "ampere/postgresql"
      - "ampere/minio"
      - ingress-nginx/ingress-nginx

  - name: airflow-spark-rbac
    chart: ./services/airflow-spark-rbac
    namespace: "{{ .Environment.Values.global.namespace }}"
    createNamespace: true
    labels:
      app: airflow-spark-rbac
      tier: workflow
    values:
      - services/airflow-spark-rbac/airflow-spark-rbac.values.yaml.gotmpl

  - name: ivy-cache
    chart: ./services/ivy-cache
    namespace: "{{ .Environment.Values.global.namespace }}"
    createNamespace: true
    labels:
      app: ivy-cache
      tier: storage
    values:
      - services/ivy-cache/ivy-cache.values.yaml.gotmpl

  - name: ingress-resources
    chart: ./services/ingress
    namespace: "{{ .Environment.Values.global.namespace }}"
    createNamespace: true
    labels:
      app: ingress
      tier: infra
    values:
      - services/ingress/ingress.values.yaml.gotmpl
    hooks:
      - events: ["preapply"]
        command: "bash"
        args:
          - "-c"
          - "sops -d services/ingress/ca.secret.yaml | kubectl apply -f -"
    needs:
      - cert-manager/cert-manager
      - ingress-nginx/ingress-nginx

  - name: keda
    chart: kedacore/keda
    version: 2.16.0
    namespace: keda
    createNamespace: true
    labels:
      app: keda
      tier: infra
    values:
      - services/keda/keda.values.yaml.gotmpl

  - name: postgresql
    chart: ./services/postgresql
    namespace: ampere
    createNamespace: true
    labels:
      app: postgresql
      tier: database
    values:
      - services/postgresql/postgresql.values.yaml.gotmpl
    secrets:
      - services/postgresql/postgresql.credentials.yaml

  - name: minio
    chart: ./services/minio
    namespace: ampere
    createNamespace: true
    labels:
      app: minio
      tier: storage
    values:
      - services/minio/minio.values.yaml.gotmpl
    hooks:
      - events: ["preapply"]
        command: "bash"
        args:
          - "-c"
          - "sops -d services/minio/minio.credentials.yaml | kubectl apply -n ampere -f -"

  - name: airflow
    chart: apache-airflow/airflow
    version: 1.18.0
    namespace: ampere
    createNamespace: true
    labels:
      app: airflow
      tier: workflow
    values:
      - services/airflow/airflow.values.yaml.gotmpl
    secrets:
      - services/airflow/airflow.credentials.yaml
      - services/airflow/airflow.webserver-secret.yaml
    hooks:
      - events: ["preapply"]
        command: "bash"
        args:
          - "-c"
          - "sops -d services/airflow/git-credentials.yaml | kubectl apply -n ampere -f -"
    needs:
      - keda/keda
      - "{{ .Environment.Values.global.namespace }}/airflow-spark-rbac"
      - "ampere/postgresql"
