{{- if and (.Capabilities.APIVersions.Has "cert-manager.io/v1/ClusterIssuer") (.Values.tls.bootstrap.enabled | default false) }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
{{- end }}
