apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Values.gateway.namespace }}
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.listeners.httpPort }}
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: {{ .Values.gateway.listeners.httpsPort }}
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: {{ .Values.tls.sharedSecret }}
      allowedRoutes:
        namespaces:
          from: All
