apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "{{ .Values.tcp.postgresPort }}": "{{ .Values.namespace }}/{{ .Values.tcp.postgresService }}:{{ .Values.tcp.postgresPort }}"
