webserver:
    defaultUser:
        email: ENC[AES256_GCM,data:KVdmvfj1NG1pAmjJgByn4wj8mpTi,iv:Jij/NH0y1iISxhSuF5P1GDaF2qRohLpKlgDWO7R318I=,tag:ev0/xGXx2eR5JDBd25nlJw==,type:str]
        firstName: ENC[AES256_GCM,data:KwWzY0E=,iv:ClU5xQlAzEwY7WhkhTozGXNrSeuLpI13q484QhaglEA=,tag:89iBIe32T8mM6Tcc5xzsNA==,type:str]
        lastName: ENC[AES256_GCM,data:0w==,iv:8N2HbonNUO0Ru2Cl9nADBbe/Vuvfb5AqR4GFTMUk7Yo=,tag:Un5f7Lkx7HWte32dXm0JRA==,type:str]
        username: ENC[AES256_GCM,data:U28vnslPDw==,iv:wAbSR7DHM6TB4lC+amM8q1yRm9heNYDJzM0uLkxJQoc=,tag:mow0tbDPZV0pLSNdz9o6TA==,type:str]
        password: ENC[AES256_GCM,data:EffNm8Csrd/0,iv:I/6EFGYI9+RbiW+zAzat+iNfRMLVJcNfj0YY16udzjs=,tag:xehir192FBmoXBRV3MSfzA==,type:str]
        role: ENC[AES256_GCM,data:g6VG9aU=,iv:OQnsq1JzXEhW7Vcj1ZMFdP/2x0ZaQNGSIFRgfJ2zrGk=,tag:UvKJ7xvJ8WtAouMrk7OAxQ==,type:str]
data:
    metadataConnection:
        pass: ENC[AES256_GCM,data:7A/VMFPGjqWDgg==,iv:oy/Zk1n2cUbOCMclevh8lyH2V4PZrYlqnZ8fYCZm7N8=,tag:9e+pxpmTr1H/WHFFu2K7iA==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2025-12-13T13:57:25Z"
          enc: FPzejxJ8VlzmssLgAc5bU4YrNyHwT0qptM9PU5bxb6gaT_qn4IzvCf5U1PqMIM4h2JTVgKW9HUu1KtKVUPZKdBIByCCF4zpsPnfkV9ypDp5ZwZ3JVgxPDbnHXwHrhl7PWd-8v6Uyy3CB1fv0_lM2qLGozioHoIEL1iX-YahHlpJIltCYKWSfoSBS_fYmc_HKpf8ywhdn_OcvKtnPhP4yNKDei0T4WeqHSTzi_D-1hYkS43XAbZrGIGgLzYYrAD503VwFuc-nr7aCMppJLaPIhnuj2X3Yt89m5FxbEb1icaY6GIuZ2-nnpafNnXGT6kPJmbvNfNadWPnV5PZJhXOOcA
    lastmodified: "2025-12-13T13:57:28Z"
    mac: ENC[AES256_GCM,data:Ry5m22H1jSC6VfItJUMgRwacf89GHy3dN7x02Owg7UJZBe4cOlrDZaw803OfoIdegBFwesqLfL5k3cjWyG77+8wQ4pI+2+UUZG2w7UirVVp3Vbu0IwMr2ONu+WG1kAOvbkP5BenYF60poEDRehjYwOjaTXQsbUOHmuifaip8WkI=,iv:LnO0oEL4O5EgwXkRmvq+1l8F/quXudkoKv+xtmqvZT4=,tag:T3rTQNa7TkgbcWqavTCAKQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
