secretStore:
    tenantId: ENC[AES256_GCM,data:ueVwF58SLeMlUMzFvXrF4tcv9sRYuquiFDPgwqZvvG4SwzTJ,iv:IBD04PaMzIOv1gB4yvL6pl6G9/0F/z92ckpn0jdRz2c=,tag:eDxmvqFb+LXmHvhcE8z88Q==,type:str]
    vaultUrl: ENC[AES256_GCM,data:+R9siA4ZVEo+3WvxWo/QLTvgAzgpxvMKvtC5BeRF+uZLQd8+0A==,iv:ENZD21YxVmt/DwwppU86hRbuvQ6W2J9eaZWD7Ju4vdE=,tag:LVf8oEVsZ22g50cAljeygg==,type:str]
credentials:
    clientSecret: ENC[AES256_GCM,data:GHFeDJJ6Yhga/BALuKGDErGoeVrBMi0San0Sqoh/z7Ts/B/2fGKdrA==,iv:gB+xfCFeo5+eALnBOIKqh+IIdyXQvEd5ygx83QiTM4Q=,tag:28ZqTMnYpl3p3fI+jfp5Dw==,type:str]
    clientId: ENC[AES256_GCM,data:2a30w8pwOjK0ssbVGjH7bJkTCSdSBAF27LZ/X3ZLp2TTiXDL,iv:Hl4uCnGjCk8udDpMCPv2Hk9/WRAD93fhF4WR4zI2Aaw=,tag:0x2qOi9guMrZAY+yI0GIww==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2026-10-04T21:12:42Z"
          enc: c1Ev3n8iMNvMFDZL59hajSIafvyzlILmzaegFp6EYFkwp0t3h3LdLLAqLc1-51anW5NI40gAN4wVIIgCxpL5-c57cRwtRb2Nis5eOjvTDGWN_ILWQw3g5ap9_CSU8Yz3bTE0BL71no9A76zCRw0ZW5odIGue91X0ic0BeCfut7QubnPnJgVrqocgLlq0gcLttE-F0SsIs6R4MnbHmiiv1zL9Zqip-89CArG6MFMFnWnQZJb-xN0pvbF6YaXtf_StmlNUkOZyqNGJP7rZnFN5cbkfV1XKA8To_5PcWl7GH1v8y5LZMdYZncTLS2sIJkuDth0wkcUhrsHRTxgwyxokTA
    lastmodified: "2026-10-04T21:12:45Z"
    mac: ENC[AES256_GCM,data:eycjkNdGrdfZdQWmRjyH3xVrlbTnjStvS7Wq7zJxHNf0yrgSgzPUGK6/L+lYmMrmJsMkdnpj9PpzrceWiq3KXpR3NbXyOyTJVvCfeyE+Z+glzQGxsRY/U1Ts9LEYC1gb5nma48eM8z712eBJaZI382iNJfMj847vlMx5/spjvBg=,iv:30H9pwADlJHDw8HIzrlvW4WvILQNxhlCyrme+UACaKE=,tag:O9lrnn73iG3C69dVF6yaVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
