apiVersion: ENC[AES256_GCM,data:eCM=,iv:IoJ+RS+6h1C/98t8O2lAJEJPDRiu+egynxSbEaxSZKw=,tag:wECCvwvfma3AoVSgKd/aLw==,type:str]
kind: ENC[AES256_GCM,data:wwwPBzZZ,iv:QgyMEFpGKuENS7Q7FAMtlLlASQ8jOKFL0A8FZnBddjg=,tag:AOBm6IlUN2j81TIW8qo3SA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:O4cwT1VX/sqO60w=,iv:4gyavZoFsBGoVaS/8lDpg3eFoTThdxF9iG3V7NqHvso=,tag:v5KzIsNEDbKdmbep7G6Hag==,type:str]
    namespace: ENC[AES256_GCM,data:fb/KbdS9,iv:h11bW3IoGP4FzM6vj9TJMnYYpJeyUPzl/r+VB5XD498=,tag:Gc+RThdA4ZUvhQKAPc5RoQ==,type:str]
type: ENC[AES256_GCM,data:Vjp4aGYm,iv:9nJ8/tlW2jcor4kbojm2O7+cWg7PnAouqm91V1WnpTQ=,tag:dIOqUyBi+Dhm4OTYSoo6ag==,type:str]
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:BjAHE8pIQw==,iv:tEfQfSzfMzz3rdhAzeaK3JBe5N5Bq2trwC2aURiL32Y=,tag:a2V2kIrWVlwddIRfJ7u6Ww==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:FpGXpBW1fwwC,iv:Mu1J+rw0Z6El+EGFOVBkqK1JnbrN3iIsmZljyt+9Xjk=,tag:RRPJ8shlkNFZcjl6kcu3iw==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2025-12-24T19:06:38Z"
          enc: FhAAU_Szn8FpkwalpkyVVU7DlxlZkLwYVWhpj78NNLKKmFM94kdunm8UXaNhipAnPqs6jOxQFl7HfmzpQxc_BcUZtpcHfMzv1ISJgg2sy-8Swp57s_hV8GutBfuml_MhFwCBijIVGntTcXvK-s161NmzWNHP3VOd2EsfpHG--TvEW3RAMNPG7ImSFJJBqMR7oOgqSelYPHaO-MEGJSWBkk4HtqqymdSXvEtDLnI5uEryMtSm6sjSfZgi9Duf4hWChFXq6ATQ-VOtshFHUQoSADNPc4o5oF6BuPjNVuEiI_6TF8rjnGxsi1ABwPOou2_oVNpJhhrVVokOgkC5IvBG5Q
    lastmodified: "2025-12-24T19:06:43Z"
    mac: ENC[AES256_GCM,data:1WTGXZnBPC1a9havTQuOQSzumoe6vgZFcju0wbZdtqJFIBTlOByOhAuHhXrKqR97xG2Cw3FLtmyxuJ3uCeZtSw4yKMZkZQMBvgKaR/eSM8XijR0LrxPiKY6vJFQ/ygQi7sdKLSeq1z4Nwbfft+3L8odSps9+mXkqayhYuW7jrjQ=,iv:yrgsVRdPThCQlIlczLZSXoSGoM+MPk0oRFblQk4dV0I=,tag:GMOpG3crUJ/AFR/0Zi3oow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
