{{- if .Values.enabled }}
{{- if .Values.dedicatedCredentials }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lakekeeper-flight-client-dedicated
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: {{ .Values.dedicatedSecrets.lakekeeper }}
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: ampere-flight-sql-lakekeeper-client-id
    - secretKey: client-secret
      remoteRef:
        key: ampere-flight-sql-lakekeeper-client-secret
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flight-sql-minio-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: {{ .Values.dedicatedSecrets.minio }}
    creationPolicy: Owner
  data:
    - secretKey: MINIO_ACCESS_KEY
      remoteRef:
        key: ampere-flight-sql-minio-access-key
    - secretKey: MINIO_SECRET_KEY
      remoteRef:
        key: ampere-flight-sql-minio-secret-key
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lakekeeper-flight-client
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: {{ .Values.secrets.lakekeeper }}
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: ampere-iceberg-curie-clientid
    - secretKey: client-secret
      remoteRef:
        key: ampere-iceberg-curie-secret
{{- end }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ampere-flight-sql-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: SecretStore
  target:
    name: {{ .Values.secrets.flightToken }}
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: ampere-flight-sql-token
{{- end }}
