
# netplan configuration generated by Terraform
network:
  version: 2
  ethernets:
    ${network.network_interface}:
      dhcp4: no
      addresses:
        - ${ip}/${network.network_prefix}
      routes:
        - to: default
          via: ${network.network_gateway}
      nameservers:
        addresses:
%{ for addr in network.network_dns ~}
          - ${addr}
%{ endfor ~}
