apiVersion: v1
kind: Secret
metadata:
  name: {{ required "secretStore.secretName is required" .Values.secretStore.secretName }}
  namespace: {{ required "secretStore.namespace is required" .Values.secretStore.namespace }}
type: Opaque
stringData:
  clientId: {{ required "credentials.clientId is required" .Values.credentials.clientId | quote }}
  clientSecret: {{ required "credentials.clientSecret is required" .Values.credentials.clientSecret | quote }}
