{{- if and .Values.resources.enabled .Values.externalSecrets.items (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1/ExternalSecret") }}
{{- $refreshPolicy := .Values.externalSecrets.refreshPolicy | default "OnChange" -}}
{{- $refreshInterval := .Values.externalSecrets.refreshInterval | default "0" -}}
{{- range .Values.externalSecrets.items }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ required "externalSecrets.items[].name is required" .name }}
  namespace: {{ required "secretStore.namespace is required" $.Values.secretStore.namespace }}
spec:
  refreshPolicy: {{ $refreshPolicy }}
  refreshInterval: {{ $refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "secretStore.name is required" $.Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .targetName | default .name }}
    creationPolicy: {{ .creationPolicy | default "Owner" }}
{{- if .targetTemplate }}
    template:
{{ toYaml .targetTemplate | nindent 6 }}
{{- end }}
  data:
{{- range .data }}
    - secretKey: {{ required "externalSecrets.items[].data[].secretKey is required" .secretKey }}
      remoteRef:
        key: {{ required "externalSecrets.items[].data[].remoteKey is required" .remoteKey }}
{{- if .property }}
        property: {{ .property }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
