apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MINIO_ACCESS_KEY: {{ .Values.MINIO_ACCESS_KEY | b64enc | quote }}
  MINIO_SECRET_KEY: {{ .Values.MINIO_SECRET_KEY | b64enc | quote }}