apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.name" . }}-env
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.username | quote }}
  POSTGRES_PASSWORD: {{ required "auth.postgresPassword is required" .Values.auth.postgresPassword | quote }}
  AIRFLOW_DB_USER: {{ .Values.users.airflow.username | quote }}
  AIRFLOW_DB_PASSWORD: {{ required "auth.password is required (airflow DB user password)" .Values.auth.password | quote }}
  AIRFLOW_DB_NAME: {{ .Values.users.airflow.database | quote }}
  OPERATIONAL_DB_USER: {{ .Values.appUsers.operational_database.user | quote }}
  OPERATIONAL_DB_PASSWORD: {{ required "appUsers.operational_database.password is required (operational DB user password)" .Values.appUsers.operational_database.password | quote }}
  OPERATIONAL_DB_NAME: {{ .Values.appUsers.operational_database.database | quote }}
