apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ include "postgresql.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgresql.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgresql.name" . }}
    spec:
{{- with .Values.securityContext }}
      securityContext:
{{- if .runAsUser }}
        runAsUser: {{ .runAsUser }}
{{- end }}
{{- if .runAsGroup }}
        runAsGroup: {{ .runAsGroup }}
{{- end }}
{{- if .fsGroup }}
        fsGroup: {{ .fsGroup }}
{{- end }}
{{- if .fsGroupChangePolicy }}
        fsGroupChangePolicy: {{ .fsGroupChangePolicy | quote }}
{{- end }}
{{- end }}

{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | nindent 8 }}
{{- end }}

{{- with .Values.volumePermissions }}
{{- if .enabled }}
      initContainers:
        - name: volume-permissions
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command:
            - sh
            - -c
            - chown -R 999:999 /var/lib/postgresql/data || true
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
{{- end }}
{{- end }}

      containers:
        - name: postgresql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "postgresql.name" . }}-env
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d postgres -h 127.0.0.1 -p 5432
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6

{{- with .Values.resources }}
          resources:
{{ toYaml . | nindent 12 }}
{{- end }}

          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d

      volumes:
        - name: initdb
          configMap:
            name: {{ include "postgresql.name" . }}-initdb
            defaultMode: 0755

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
{{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName | quote }}
{{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
