webserver:
    defaultUser:
        email: ENC[AES256_GCM,data:RnmheNxX/wQ4WjL+wuyh5mvD0PQS,iv:6NXEJs0f/+p0RhEfu6bJ44snjv4JTczOY3AyaNMhGGc=,tag:5XdawvJFnbraIq8FRvTYSw==,type:str]
        firstName: ENC[AES256_GCM,data:+AgRy9w=,iv:G2bEhwGVx0dgpqGaoU1o58WfCuCEIWL5IKTQzCGdhg4=,tag:dLOTqafJPQCsSalt7T29Sg==,type:str]
        lastName: ENC[AES256_GCM,data:tw==,iv:LLyMdKwUZ82vBjNOuTAse2doz09NsiFULD8cxca93UE=,tag:/PjxMxz/j7H01pXbYQ6ELg==,type:str]
        username: ENC[AES256_GCM,data:EkH5uewTQg==,iv:BAmgXyz/MDU2pI36Q1TebHRlCbtTdsh0icR7pTRHF7g=,tag:wWwlaTwxLF9w/G8ZlmR0jw==,type:str]
        password: ENC[AES256_GCM,data:c5uesReslsgd,iv:4DSxf2opHT+k9PWVLamAGFovzpUstkABzE3bqYDW2vA=,tag:O+LXQZ9RB3ZOFtFb5oeAbA==,type:str]
        role: ENC[AES256_GCM,data:4b3/ajw=,iv:i0ITxiyKpO5BmUolIp72+8tUh5dfl5A4+hshlSK/Ayg=,tag:4Kts0GqMah7TCv/QbpJTNw==,type:str]
data:
    metadataConnection:
        pass: ENC[AES256_GCM,data:sUakifzElJxmqA==,iv:o0pg/LfKRWcunG4Gvjh3NwHtSJhiDQpahblQ3xgXuw4=,tag:tJjS3OTFovnjB58HBMIxEg==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2025-12-14T18:49:25Z"
          enc: Sa_TYXOB8O8-GYthTH9GRfJp0o8KmyF0tvCOPpY6Q7uEe34h4IpIqQccRyQhFc_Lj0TNfscNM7GXPe-lrvcWotRobVTEn14jeFNcgy9p25-kg2T0ysH8mVJZW_lrBZQ-S5wPmPIkUoP5uUyBlp_-HG89nt7gFqFlbiAvPlHXX6wAjja5qM3Hw3PRgjqYdqu-x0n2RAU8-dINYDYBSwl7BXziYIBlTiW7Wcn5S1OrWGfv3-kZ-JPqIKzxNUprspSm9ZiLGf294n448pcilmDeRSId1c7VM5O25xdTUn5yRxRwsWLoaze_SW9YC3ipQYrDzx9up1PA0iiB4UA6K0gbbw
    lastmodified: "2025-12-14T18:49:28Z"
    mac: ENC[AES256_GCM,data:Q/eEIqr/Np5mAfKQazPWXrqheDFquJfybbJjEbmPh+lKWsMbgQ+csutj1R02bkDkHqjVUrqL5BWIBzl5x/HbQnJ8hhPgm8DOmqtzBwzPE7nxYxngcvlnwYghwYz1HvsYWvsWjpzLgbJJ8CDuh4B+0X6lHYCCr8LSzfwaDkewarA=,iv:i0W8nQz+Gm3zRsAzD8CMTgZvdxBIWamz4OgEnwJhVLg=,tag:R+BogyYQudfxqs+dCXUafw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
