apiVersion: ENC[AES256_GCM,data:tvE=,iv:m0muoUIqcLtGKQiLufwAJkE3VJ58j/o+AZRTTKWsgwk=,tag:/qTj0jcA9HgScR8AoJtjRg==,type:str]
kind: ENC[AES256_GCM,data:tU4hJ/Rp,iv:jRL/PQ+zdNpIL7qvaqUqwmRrMou4+PtMdXe4edbRlG0=,tag:tPaksumtODmyTeVfyAcDrw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:lIZRJ0O76dAV1XJg14mOBkrzbaURw9l1,iv:VAtmuipaDZduU0JLyM6HPDrhDnMfWetyK2/BRRbQ54g=,tag:jCvBybSawV6mQ8yZ25QAeA==,type:str]
    namespace: ENC[AES256_GCM,data:Z6L2fbhg,iv:2D9cU8NeMX0lvjoCdf7UDmzwJSLiZpfizlXuQspfP8U=,tag:giwYE3luO1aApnpS1m2UcQ==,type:str]
type: ENC[AES256_GCM,data:qZ5ySq6D,iv:x9Ow9i7xqpr8bdRsQC+5/d/MqqdazrG9HhCMIuLc6ws=,tag:muQmjkVhuaxMBBMzqB8Q9g==,type:str]
stringData:
    webserver-secret-key: ENC[AES256_GCM,data:i+QddkBPFM03vLSnHXZxfcpQDPkI+lwoudYZSbKC3iE=,iv:/pqSCMDBLVBVg3vs2ImYFqVpysY016iMtgpDIqeE/0E=,tag:BQVMEfHgHRoqERCmhlX/kg==,type:str]
sops:
    azure_kv:
        - vault_url: https://az-ampere-kv.vault.azure.net
          name: sops-key
          version: c1f32e2e99064a1582e1741109ca0f06
          created_at: "2025-12-22T21:24:38Z"
          enc: Y0wxUnsM2nkJ4FPhY1cQzrw7GRZLEPDcIGuer2Hi0jHhxs009RZHIXpfvzLnBVPZQaXrZPRzG6Z92rBnhOjkdsdreWuB8j8QgC294MCT0vd_jtnz4uzpZLHTU4aUWVNeLBQWX3QVNu3cdKhR3PZVj_NbXUHGA44JLvl88sGOCfwvWi5HSDG1_Xo1KLOuOWmu9BGs3qYEHG1S4x8uuIUdDMSQOddSRHKJVxF0KeklmJfwC4l5oAgkDsJlpkG_Dz6nHwSsKwt17S6DQXJJHB6Yxz4SSwoym_zm3lcfpb-ttOcF1S54xGYdZAk3QBFQfuOuOIM8FqD7k5PPQzj_BVygIg
    lastmodified: "2025-12-22T21:24:43Z"
    mac: ENC[AES256_GCM,data:6qCL42v6chga/dl7fWqY7EZ7qGMFGf2HrmS/M4pehhs1XuM83eCxLDBZ6ISV3L0lWPUuI1lmzEvEcYO3Yzu8HrdI7iwNGIX3nzgExpAEZmiLfHUs2vllhcfYSwiMEVvuLjc/TrWf9y8K4JFT3bGOubK/8jmyZM/VyRdL6IYgWxk=,iv:VRqTK/HXVz5DaH/AWi/FXUB3SiDRNo9crgekrxpQEyc=,tag:cwAvkpMNNtgLhvieKn5rVQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
