apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-source
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: 1Gi
