apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv-tailscale
spec:
  conditions:
    - namespaces:
        - tailscale
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: {{ required "tenantId is required" .Values.tenantId | quote }}
      vaultUrl: {{ required "vaultUrl is required" .Values.vaultUrl | quote }}
      authSecretRef:
        clientId:
          name: {{ .Values.existingAzureCredential.name }}
          key: clientId
          namespace: {{ .Values.existingAzureCredential.namespace }}
        clientSecret:
          name: {{ .Values.existingAzureCredential.name }}
          key: clientSecret
          namespace: {{ .Values.existingAzureCredential.namespace }}
